# Generated by Django 3.0.2 on 2020-03-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_customuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
    ]
